# Generated by Django 5.1.4 on 2025-01-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_remove_post_author_remove_post_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
    ]
