# Generated by Django 5.1.4 on 2025-01-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complected',
            new_name='status',
        ),
    ]
